[package]
name = "Rust-Training"
version = "0.1.0"
edition = "2021"
authors = ["Pedro Braga <pedrobragaom@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "Rust-Training"
path = "main.rs"
